---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.3

platforms:
  - name: windows-2012r2
    driver:
      box: dhoer/windows-2012r2
      network:
      - ["forwarded_port", {guest: 4444, host: 5444}]

suites:
  - name: default
    run_list:
      - recipe[iedriver_test::default]
    attributes:
